version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GIT_0104Project
  gitServerName: rimaSCName
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
- name: WmJDBCAdapter
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
services:
- serviceName: project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:Database_1_rb0104
  packages:
  - name: SIQA_GIT_0104Project
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:Database_2_rb_Test
  packages:
  - name: SIQA_GIT_0104Project
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.siqa_git_0104.integrations:SIQAAdapterFlow
  packages:
  - name: SIQA_GIT_0104Project
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
configurationVariables:
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2_rb_Test.connectionSettings.password
  : "{AES}X4QCAWgjWkTdMQvFA5XaqGmK1wuN3U1rA1B0VhuZoUw="
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_rb0104.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_rb0104.connectionSettings.serverName
  : 9.46.196.248
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_rb0104.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2_rb_Test.connectionSettings.datasourceClass
  : com.wm.dd.jdbcx.sqlserver.SQLServerDataSource
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_rb0104.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_rb0104.connectionSettings.portNumber
  : "3306"
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2_rb_Test.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2_rb_Test.connectionSettings.dbType
  : MSSQL
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2_rb_Test.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_rb0104.connectionSettings.otherProperties
  : loginTimeout=60;driverType=thin;
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_rb0104.connectionSettings.networkProtocol
  : tcp
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_rb0104.connectionSettings.datasourceClass
  : com.mysql.cj.jdbc.MysqlDataSource
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_rb0104.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2_rb_Test.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2_rb_Test.connectionManagerSettings.minimumPoolSize
  : "1"
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_rb0104.connectionSettings.dbType
  : MySQL
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2_rb_Test.connectionSettings.serverName
  : 9.60.195.99
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_rb0104.connectionSettings.user
  : siqatest
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2_rb_Test.connectionSettings.otherProperties
  : loginTimeout=60;driverType=thin;
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2_rb_Test.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_rb0104.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2_rb_Test.connectionSettings.keyStore
  : ""
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2_rb_Test.connectionSettings.networkProtocol
  : tcp
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_rb0104.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2_rb_Test.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_rb0104.connectionEnabled
  : "false"
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_rb0104.connectionSettings.trustStore
  : ""
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2_rb_Test.connectionSettings.portNumber
  : "1433"
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2_rb_Test.connectionSettings.transactionType
  : NO_TRANSACTION
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2_rb_Test.connectionSettings.user
  : sa
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_rb0104.connectionSettings.password
  : "{AES}D6/2AGfsSWDOcWCLrORnEQ=="
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2_rb_Test.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2_rb_Test.connectionSettings.databaseName
  : SIQACloud
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2_rb_Test.connectionEnabled
  : "false"
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2_rb_Test.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2_rb_Test.connectionSettings.trustStore
  : ""
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2_rb_Test.connectionSettings.driverType
  : Progress® DataDirect®
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_2_rb_Test.connectionManagerSettings.poolable
  : "false"
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_rb0104.connectionSettings.transactionType
  : NO_TRANSACTION
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_rb0104.connectionManagerSettings.poolable
  : "false"
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_rb0104.connectionSettings.driverType
  : TestDriver
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_rb0104.connectionSettings.databaseName
  : MYSQL_DATABASE
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_rb0104.connectionSettings.keyStore
  : ""
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_rb0104.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.SIQA_GIT_0104Project.project.siqa_git_0104.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_rb0104.connectionManagerSettings.minimumPoolSize
  : "1"
